import type { SkillId } from "../model/types";
import type { SkillDef } from "./types";

export const skillDefs: Record<SkillId, SkillDef> = {
  whirlwind: {
    id: "whirlwind",
    type: "active",
    name: "旋风斩",
    description: "对周围敌人造成范围伤害。",
    unlockLevel: 1,
    maxLevel: 100,
    branchUnlockLevel: 0,
    branches: [],
    baseCooldownMs: 4500,
  },
  charge: {
    id: "charge",
    type: "active",
    name: "冲撞",
    description: "冲锋至屏幕最右侧再返回，造成2次伤害。",
    unlockLevel: 1,
    maxLevel: 100,
    branchUnlockLevel: 0,
    branches: [],
    baseCooldownMs: 10000,
  },
  thunder: {
    id: "thunder",
    type: "active",
    name: "雷霆一击",
    description: "以自身为中心释放雷霆，范围与旋风斩一致。",
    unlockLevel: 1,
    maxLevel: 100,
    branchUnlockLevel: 0,
    branches: [],
    baseCooldownMs: 6000,
  },
  berserk: {
    id: "berserk",
    type: "active",
    name: "狂暴",
    description: "体型急剧增大并获得额外吸血，持续一段时间。",
    unlockLevel: 1,
    maxLevel: 100,
    branchUnlockLevel: 0,
    branches: [],
    baseCooldownMs: 3000,
  },
  shield_wall: {
    id: "shield_wall",
    type: "active",
    name: "盾墙",
    description: "在持续时间内将荆棘触发率提升至100%。",
    unlockLevel: 1,
    maxLevel: 100,
    branchUnlockLevel: 0,
    branches: [],
    baseCooldownMs: 30000,
  },
};
